try : it is used to try keep the code segament under the try (code error)

except : this segament is used to handle the exception after catching its (which is type of error)

else : run this when no acception  exits ( no error)

finally : no matter what's run this code will be executed (always run )


example :

# list=[10,20,30]
# #print(list)
# try:
#     print(list[4])
# except IndexError as msg:
#     print("find the error :- ",msg)
# else:
#     print("there is no error")
# finally:
#     print("no matter what it is,program done")